gestorAppTG/gestorAppTG/urls.py
from django.contrib import admin
from django.urls import include,path

#HERICK: importamos todas nuestras vistas aqui 
from .views import gestorAppTG
from .views import propuestas
from .views import user
from .views import tesis
from .views import termin
from .views import defensa
from .views import escuela
from .views import estatusTG
from .views import estatusPropuesta
from .views import reporte
from .views import tranzabilidad

urlpatterns = [
    
    path('', gestorAppTG.home, name='home'),

    path('accounts/', include('django.contrib.auth.urls')),
    
    path('admin/', admin.site.urls,  name="admin"),
    
    path('propuestas/', include(([
        path('', propuestas.IndexView.as_view(), name='propuestas_list'),
        path('<int:pk>/update/', propuestas.UpdatePropuestaView.as_view(), name='propuestas_update'),
        path('search/', propuestas.BusquedaPropuesta.as_view(), name='propuestas_search'),
        path('create/', propuestas.CreatePropuestaView.as_view(), name='propuestas_create'),
        path('<int:pk>/', propuestas.DetailView.as_view(), name='propuestas_details'),
		path('<int:pk>/delete/', propuestas.DeletePropuestaView.as_view(), name='propuestas_delete'),
        path('export/xls/', propuestas.Export_propuesta_xls.export_propuesta_xls, name='export_propuesta_xls'),
    ], 'gestorAppTG'), namespace='propuestas')),

    path('users/', include(([
        path('', user.IndexView.as_view(), name='users_list'),
        path('search/', user.BusquedaUsuario.as_view(), name='users_search'),
        path('<int:pk>/', user.DetailView.as_view(), name='users_details'),
        path('create/', user.CreateUserView.as_view(), name='users_create'),
        path('<int:pk>/update/', user.UpdateUserView.as_view(), name='users_update'),
        path('<int:pk>/updatePass/', user.UpdateUserPassView.as_view(), name='users_updatePass'),
        path('<int:pk>/delete/', user.DeleteUserView.as_view(), name='users_delete'),
        path('export/xls/', user.Export_users_xls.export_users_xls, name='export_users_xls'),
    ], 'gestorAppTG'), namespace='users')),

    path('tesis/', include(([
        path('', tesis.IndexView.as_view(), name='tesis_list'),
        path('search/', tesis.BusquedaTesis.as_view(), name='tesis_search'),
        path('create/', tesis.CreateTesisView.as_view(), name='tesis_create'),
        path('<str:pk>/', tesis.DetailView.as_view(), name='tesis_details'),
        path('<str:pk>/update/', tesis.UpdateTesisView.as_view(), name='tesis_update'),
        path('<str:pk>/delete/', tesis.DeleteTesisView.as_view(), name='tesis_delete'),
        path('export/xls/', tesis.Export_tesis_xls.export_tesis_xls, name='export_tesis_xls'),
    ], 'gestorAppTG'), namespace='tesis')),

    path('defensas/', include(([
        path('', defensa.IndexView.as_view(), name='defensas_list'),
        path('search/', defensa.BusquedaDefensa.as_view(), name='defensas_search'),
        path('create/', defensa.CreateDefensaView.as_view(), name='defensas_create'),
        path('<str:pk>/', defensa.DetailView.as_view(), name='defensas_details'),
        path('<str:pk>/update/', defensa.UpdateDefensaView.as_view(), name='defensas_update'),
        path('<str:pk>/delete/', defensa.DeleteDefensaView.as_view(), name='defensas_delete'),
        path('export/xls/', defensa.Export_defensa_xls.export_defensa_xls, name='export_defensa_xls'),
    ], 'gestorAppTG'), namespace='defensas')),

    path('termin/', include(([
        path('', termin.IndexView.as_view(), name='termins_list'),
        path('create/', termin.CreateTerminView.as_view(), name='termin_create'),
        path('search/', termin.BusquedaTermin.as_view(), name='termin_search'),
        path('<int:pk>/update/', termin.UpdateTerminView.as_view(), name='termin_update'),
        path('<int:pk>/delete/', termin.DeleteTerminView.as_view(), name='termin_delete'),
        path('export/xls/', termin.Export_termin_xls.export_termin_xls, name='export_termin_xls')
    ], 'gestorAppTG'), namespace='termin')),

    path('estatusPropuestas/', include(([
        path('', estatusPropuesta.IndexView.as_view(), name='estatusPropuestas_list'),
        path('create/', estatusPropuesta.CreateEstatusPropuestaView.as_view(), name='estatusPropuestas_create'),
        path('<int:pk>/update/', estatusPropuesta.UpdateEstatusPropuestaView.as_view(), name='estatusPropuestas_update'),
        path('<int:pk>/delete/', estatusPropuesta.DeleteEstatusPropuestaView.as_view(), name='estatusPropuestas_delete'),
        path('export/xls/', estatusPropuesta.Export_estatusPropuesta_xls.export_estatusPropuesta_xls, name='export_estatusPropuesta_xls')
    ], 'gestorAppTG'), namespace='estatusPropuestas')),

    path('estatusTGs/', include(([
        path('', estatusTG.IndexView.as_view(), name='estatusTGs_list'),
        path('create/', estatusTG.CreateEstatusTGView.as_view(), name='estatusTGs_create'),
        path('<int:pk>/update/', estatusTG.UpdateEstatusTGView.as_view(), name='estatusTGs_update'),
        path('<int:pk>/delete/', estatusTG.DeleteEstatusTGView.as_view(), name='estatusTGs_delete'),
         path('export/xls/', estatusTG.Export_estatusTGs_xls.Export_estatusTGs_xls, name='export_estatusTGs_xls')
    ], 'gestorAppTG'), namespace='estatusTGs')),

    path('escuelas/', include(([
        path('', escuela.IndexView.as_view(), name='escuelas_list'),
        path('create/', escuela.CreateEscuelaView.as_view(), name='escuelas_create'),
        path('<int:pk>/update/', escuela.UpdateEscuelaView.as_view(), name='escuelas_update'),
        path('<int:pk>/delete/', escuela.DeleteEscuelaView.as_view(), name='escuelas_delete'),
        path('export/xls/', escuela.Export_escuela_xls.Export_escuela_xls, name='export_escuela_xls')
    ], 'gestorAppTG'), namespace='escuelas')),

    path('tranzabilidad/', include(([
        path('', tranzabilidad.IndexView.as_view(), name='tranzabilidads_list'),
        path('search/', tranzabilidad.BusquedaTranzabilidad.as_view(), name='tranzabilidads_search'),
        path('export/xls/', tranzabilidad.Export_tranzabilidad_xls.Export_tranzabilidad_xls, name='export_tranzabilidad_xls')
    ], 'gestorAppTG'), namespace='tranzabilidads')),

    path('reporte1/', include(([
        path('', reporte.IndexReporte1View.as_view(), name='reporte1s_list'),
         path('export/xls/', reporte.Export_reporte1_xls.Export_reporte1_xls, name='export_reporte1_xls')
    ], 'gestorAppTG'), namespace='reporte1s')),
    path('reporte2/', include(([
        path('', reporte.IndexReporte2View.as_view(), name='reporte2s_list'),
         path('export/xls/', reporte.Export_reporte2_xls.Export_reporte2_xls, name='export_reporte2_xls')
    ], 'gestorAppTG'), namespace='reporte2s')),
    path('reporte3/', include(([
        path('', reporte.IndexReporte3View.as_view(), name='reporte3s_list'),
         path('export/xls/', reporte.Export_reporte3_xls.Export_reporte3_xls, name='export_reporte3_xls')
    ], 'gestorAppTG'), namespace='reporte3s')),
    path('reporte4/', include(([
        path('', reporte.IndexReporte4View.as_view(), name='reporte4s_list'),
         path('export/xls/', reporte.Export_reporte4_xls.Export_reporte4_xls, name='export_reporte4_xls')
    ], 'gestorAppTG'), namespace='reporte4s')),
    path('reporte5/', include(([
        path('', reporte.IndexReporte5View.as_view(), name='reporte5s_list'),
        path('export/xls/', reporte.Export_reporte5_xls.Export_reporte5_xls, name='export_reporte5_xls'),
        path('search/', reporte.Busqueda5.as_view(), name='reporte5_search'),
    ], 'gestorAppTG'), namespace='reporte5s')),
    path('reporte6/', include(([
        path('', reporte.IndexReporte6View.as_view(), name='reporte6s_list'),
        path('export/xls/', reporte.Export_reporte6_xls.Export_reporte6_xls, name='export_reporte6_xls'),
        path('search/', reporte.Busqueda6.as_view(), name='reporte6_search'),
    ], 'gestorAppTG'), namespace='reporte6s')),
    path('reporte7/', include(([
        path('', reporte.IndexReporte7View.as_view(), name='reporte7s_list'),
         path('export/xls/', reporte.Export_reporte7_xls.Export_reporte7_xls, name='export_reporte7_xls')
    ], 'gestorAppTG'), namespace='reporte7s')),
]

gestorAppTG/gestorAppTG/views/user.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.contrib import messages
from django.urls import reverse_lazy
from django.views import generic
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from ..decorador import *
from django.contrib.auth.decorators import login_required
from ..models import User, Tranzabilidad
import math
import xlwt
import datetime



@method_decorator([login_required, gestor_permisos], name='dispatch')
class IndexView(generic.ListView):
    template_name = 'user/index.html'
    context_object_name = 'list_users'
    def get_queryset(self):
        p = Tranzabilidad(tipo_de_acccion='abrio el panel de usuario', usuario=self.request.user,fecha_accion=datetime.datetime.now())
        p.save()
        return User.objects.order_by('cedula')

@method_decorator([login_required, invitado_permisos], name='dispatch')
class DetailView(generic.DetailView):
    model = User
    template_name = 'user/detail.html'

opciones=['cedula', 'esAdmin', 'esGestor', 'esInvitado', 'username', 'type', 'primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido', 'ucab_email', 'email', 'telefono', 'telefono_1', 'observaciones']
opciones1=['cedula', 'esAdmin', 'esGestor', 'esInvitado', 'username', 'password','type', 'primer_nombre', 'segundo_nombre', 'primer_apellido', 'segundo_apellido', 'ucab_email', 'email', 'telefono', 'telefono_1', 'observaciones']

@method_decorator([login_required, gestor_permisos], name='dispatch')
class BusquedaUsuario(generic.ListView):
    template_name = 'user/index.html'
    context_object_name = 'list_users'
    def get_queryset(self):
        if self.request.GET:
            cedula = self.request.GET.get('search')
            p = Tranzabilidad(tipo_de_acccion='consulta de usuario por cedular', usuario=self.request.user,fecha_accion=datetime.datetime.now())
            p.save()
            if cedula == "":
                return User.objects.order_by('cedula')
            if not str.isdigit(cedula):
                return User.objects.filter(primer_nombre__contains = str(cedula))
        return User.objects.filter(cedula__contains = int(cedula))

@method_decorator([login_required, gestor_permisos], name='dispatch')
class CreateUserView(generic.CreateView):
    model = User
    fields = opciones1
    template_name = 'user/create.html'
    def form_valid(self, form):
        user = form.save(commit=False)
        user.save()
        p = Tranzabilidad(tipo_de_acccion='creo a un usuario', usuario=self.request.user,fecha_accion=datetime.datetime.now())
        p.save()
        messages.success(self.request,  'usuario creado exitosamente')
        return redirect('users:users_list')

@method_decorator([login_required, gestor_permisos], name='dispatch')
class UpdateUserView(generic.UpdateView):
    model = User
    fields = opciones
    template_name = 'user/update.html'
    def form_valid(self, form):
        user = form.save(commit=False)
        user.save()
        p = Tranzabilidad(tipo_de_acccion='actualizo a un usuario', usuario=self.request.user,fecha_accion=datetime.datetime.now())
        p.save()
        messages.success(self.request, 'Usuario actualizado exitosamente')
        return redirect('users:users_list')

@method_decorator([login_required, gestor_permisos], name='dispatch')
class UpdateUserPassView(generic.UpdateView):
    model = User
    fields = ['username', 'password']
    template_name = 'user/updatePass.html'
    def form_valid(self, form):
        user = form.save(commit=False)
        user.savePass()
        p = Tranzabilidad(tipo_de_acccion='actualizo la contraseña de un usuario', usuario=self.request.user,fecha_accion=datetime.datetime.now())
        p.save()
        messages.success(self.request, 'contraseña actualizada exitosamente')
        return redirect('users:users_list')


@method_decorator([login_required, gestor_permisos], name='dispatch')
class DeleteUserView(generic.DeleteView):
    model = User
    template_name = 'user/delete.html'
    def get_success_url(self):
        p = Tranzabilidad(tipo_de_acccion='elimino a un usuario', usuario=self.request.user,fecha_accion=datetime.datetime.now())
        p.save()
        return reverse_lazy('users:users_list')

@method_decorator([login_required, gestor_permisos], name='dispatch')
class Export_users_xls(generic.ArchiveIndexView):
    def export_users_xls(request):
        model = User
        fields = "__all__"
        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = 'attachment; filename="users.xls"'

        wb = xlwt.Workbook(encoding='utf-8')
        ws = wb.add_sheet('Users')

        # Sheet header, first row
        row_num = 0

        font_style = xlwt.XFStyle()
        font_style.font.bold = True

        columns = ['Cedula','Primer Apellido', 'Primer nombre', 'Usuario', 'Tipo','Email ucab', 'Email','Telefono' ]

        for col_num in range(len(columns)):
            ws.write(row_num, col_num, columns[col_num], font_style)

        # Sheet body, remaining rows
        font_style = xlwt.XFStyle()
        rows = User.objects.all().values_list('cedula','primer_apellido','primer_nombre','username','type','ucab_email','email','telefono').order_by('cedula')
        
        for row in rows:
            row_num += 1
            for col_num in range(len(row)):
                ws.write(row_num, col_num, row[col_num], font_style)
        p = Tranzabilidad(tipo_de_acccion='exporto en excel los usuario', usuario=request.user,fecha_accion=datetime.datetime.now())
        p.save()
        wb.save(response)
        return response

gestorAppTG/templates/user/create.html
{% extends 'template.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <br>
  <h4 class="mb-3">Crear Usuario</h4>
  <div class="row">
    <div class=" col-sm-8 col-12 card text-left p-5" style="margin-left: 15%">
      <form id="formCreate" method="post" novalidate>
        {% csrf_token %}
        <b>{{ form|crispy }}</b>
        <div style="margin-bottom: 50px;">
            <button id="enviar" type="submit" class="btn btn-info">Guardar</button>
            <a href="{% url 'users:users_list' %}" class="btn btn-outline-info" role="button">
                Volver
            </a>
        </div>
        </form>
      </form>
    </div>
    <script type="text/javascript">
     $('#enviar').on('click', function(e){
      
      idCedula = document.getElementById('id_cedula').value;
      idUser = document.getElementById('id_username').value;
      idPass = document.getElementById('id_password').value;
      idTipo = document.getElementById('id_type').value;
      idNombre = document.getElementById('id_primer_nombre').value;
      idNombreS = document.getElementById('id_segundo_nombre').value;
      idApellido = document.getElementById('id_primer_apellido').value;
      idApellidoS = document.getElementById('id_segundo_apellido').value;
      idCorreo = document.getElementById('id_email').value;
      idTelefono = document.getElementById('id_telefono').value;
      idTelefono1 = document.getElementById('id_telefono_1').value;

      if(idCedula == ""){ swal("Error", "Falta la cedula", "error"); return false;}
      if(idUser == ""){ swal("Error", "Falta el usuario", "error");  return false;}
      if(idTipo == ""){ swal("Error", "Falta el tipo de usuario", "error");  return false;}
      if(idPass == ""){ swal("Error", "Falta la contraseña", "error"); return false;}
      if(idNombre == ""){ swal("Error", "Falta el primer nombre", "error");  return false;}
      if(idApellido == ""){swal("Error", "Falta el primer apellido", "error");return false;}
      if(idCorreo == ""){swal("Error", "Falta el correo", "error");return false;}
      if(idTelefono == ""){swal("Error", "Escriba algun numero de telefono", "error");return false;}

      e.preventDefault();
      var $thisForm = $(this).parents('form');
      swal({
        title: 'Estas seguro?',
        text: "Los datos del usuario seran guardados!",
        icon: 'warning',
        buttons: [
          'No',
          'Yes'
       ],
      dangerMode: true,
      }).then(function (isConfirm) {
          if(isConfirm){
            swal({
            title: 'Creado',
            text: 'El usuario fue creado satisfactoriamente!',
            icon: 'success'
            }).then(function() {
             $('#formCreate').submit();
            });
          }
          else{
            //
          }
      })
      });

    </script>
  </div>
{% endblock %}

gestorAppTG/templates/user/delete.html
{% extends 'template.html' %}
{% block content %}
    <form id="deleteForm" method="post">
        {% csrf_token %}
        <p>
            <br>
            <h4 class="mb-3">Eliminar Usuario</h4>
            ¿Quieres eliminar este usuario?
            <div style="margin-bottom: 50px; margin-top:10px">
                <button id="enviar" type="submit" class="btn btn-info">Guardar</button>
                <a href="{% url 'users:users_list' %}" class="btn btn-outline-info" role="button">
                    Volver
                </a>
            </div>
            <script type="text/javascript">
                 $('#enviar').on('click', function(e){
                  e.preventDefault();
                  swal({
                    title: 'Estas seguro?',
                    text: "Los datos de este usuario seran eliminados!",
                    icon: 'warning',
                    buttons: [
                      'No',
                      'Yes'
                   ],
                  dangerMode: true,
                  }).then(function (isConfirm) {
                      if(isConfirm){
                        swal({
                        title: 'Actualizado',
                        text: 'Usuario eliminado satisfactoriamente!',
                        icon: 'success'
                        }).then(function() {
                         $('#deleteForm').submit();
                        });
                      }
                      else{
                        //
                      }
                  })
                  });
              </script>
        </p>
    </form>
{% endblock %}

gestorAppTG/templates/user/detail.html
{% extends 'template.html' %}
    {% block content %}  
    <br>
    <h4>Detalles del usuario</h4>  
    <p>
        <br>
        <strong>Cédula de identidad:&nbsp;</strong> <i>{{ user.cedula }}</i><br>
        <strong>Username:&nbsp;</strong> <i>{{ user.username }}</i><br>
        <strong>Contraseñad:&nbsp;</strong> <i>{{ user.password }}</i><br>
        <strong>primer nombre:&nbsp;</strong> <i>{{ user.primer_nombre }}</i><br>
        <strong>segundo nombre:&nbsp;</strong> <i>{{ user.segundo_nombre }}</i><br>
        <strong>primer apellido:&nbsp;</strong> <i>{{ user.primer_apellido }}</i><br>
        <strong>segundo apellido:&nbsp;</strong> <i>{{ user.segundo_apellido }}</i><br>
        <strong>Correo:&nbsp;</strong> <i>{{ user.email }}</i><br>
        <strong>Correo de la UCAB:&nbsp;</strong> <i>{{ user.ucab_email }}</i><br>
        <strong>Teléfono principal:&nbsp;</strong> <i>{{ user.telefono }}</i><br>
    </p>
    <a href="{% url 'users:users_list' %}" class="btn btn-outline-info" role="button">
        Volver
    </a>
{% endblock %}

gestorAppTG/templates/user/index.html
{% extends 'template.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Personas</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            {% if user.is_authenticated %}
                {% if user.esAdmin or user.esGestor %}
                <a href="" class="btn btn-outline-info" role="button">
                    Exportar pdf
                </a>
                <a href="{% url 'users:export_users_xls' %}" class="btn btn-outline-info" role="button" style="border-radius: 0 0.25rem 0.25rem 0">
                    Exportar excel
                </a>
                    <a href="{% url 'users:users_create' %}" class="btn btn-outline-info ml-4" role="button">
                        Crear una Persona
                    </a>
                {% endif %}
            {% endif %}
        </div>
        <!--button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
          Exportar proximamente poner este boton Herick
        </button!-->
      </div>
    </div>

    <form action="{% url 'users:users_search' %}" method="GET" class="form-inline ml-3">
            <div class="cntnr-padding" style="margin-bottom: 15px;margin-top:15px;">
            <div class="row">
               <div class="">
                    <div class="input-group">
                      <input name="search" type="search" value="{{cedula}}" class="form-control" placeholder="Search for...">
                      <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">Search</button>
                      </span>
                    </div>
               </div>
               <div class="col-md-8"></div>
           </div>
        </div>
    </form>

    {% if list_users %}
        <div class="table-responsive">
           <!-- {% if messages %}
            <ul class="messages">
                {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %} -->
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th>Cedula</th>
                        <th>Usuario</th>
                        <th>Nombre</th>
                        <th>Apellido</th>

                        {% if user.is_authenticated %}
                            {% if user.esAdmin or user.esGestor %}
                                <th>Acciones</th>
                            {% endif %}
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for i in list_users %}
                    <tr>
                        <td><a href="{% url 'users:users_details' i.id %}">{{i.cedula}}</a></td>
                        <td>{{i.username}}</td>
                        <td>{{i.primer_nombre}}</td>
                        <td>{{ i.primer_apellido }}</td>
                        {% if user.is_authenticated %}
                            {% if user.esAdmin or user.esGestor %}
                            <td>
                                <a href="{% url 'users:users_update' i.id %}" style="text-decoration: none">
                                <button class="btn btn-primary">
                                Actualizar
                                </button>
                                </a>                                
                                <a href="{% url 'users:users_delete' i.id %}" style="text-decoration: none">
                                <button class="btn btn-danger">
                                Eliminar
                                </button>
                                </a>
                                <a href="{% url 'users:users_updatePass' i.id %}" style="text-decoration: none">
                                <button class="btn btn-primary">
                                Cambiar Contraseña
                                </button>
                                </a>
                            </td>
                            {% endif %}
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p>No hay personas todavia para mostrar.</p>
    {% endif %}
{% endblock %}

gestorAppTG/templates/user/update.html
{% extends 'template.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <br>
    <h4 class="mb-3">Editar persona</h4>
    <div class="row">
      <div class=" col-sm-8 col-12 card text-left p-5" style="margin-left: 15%">
        <form id="formUpdate" method="post" novalidate>
        {% csrf_token %}
        <b>{{ form|crispy }}</b>
          <div style="margin-bottom: 50px;">
            <button id ="enviar" type="submit" class="btn btn-info">Guardar</button>
            <a href="{% url 'users:users_list' %}" class="btn btn-outline-info" role="button">Volver</a>
          </div>
        </form>
        </form>
      </div>

   <script type="text/javascript">
     $('#enviar').on('click', function(e){

      idCedula = document.getElementById('id_cedula').value;
      idUser = document.getElementById('id_username').value;
      idTipo = document.getElementById('id_type').value;
      idNombre = document.getElementById('id_primer_nombre').value;
      idNombreS = document.getElementById('id_segundo_nombre').value;
      idApellido = document.getElementById('id_primer_apellido').value;
      idApellidoS = document.getElementById('id_segundo_apellido').value;
      idCorreo = document.getElementById('id_email').value;
      idTelefono = document.getElementById('id_telefono').value;
      idTelefono1 = document.getElementById('id_telefono_1').value;

      if(idCedula == ""){ swal("Error", "Falta la cedula", "error"); return false;}
      if(idUser == ""){ swal("Error", "Falta el usuario", "error");  return false;}
      if(idTipo == ""){ swal("Error", "Falta el tipo de usuario", "error");  return false;}
      if(idNombre == ""){ swal("Error", "Falta el primer nombre", "error");  return false;}
      if(idApellido == ""){swal("Error", "Falta el primer apellido", "error");return false;}
      if(idCorreo == ""){swal("Error", "Falta el correo", "error");return false;}
      if(idTelefono == ""){swal("Error", "Escriba algun numero de telefono", "error");return false;}

      e.preventDefault();
      var $thisForm = $(this).parents('form');
      swal({
        title: 'Estas seguro?',
        text: "Los datos del usuario seran modificados!",
        icon: 'warning',
        buttons: [
          'No',
          'Yes'
       ],
      dangerMode: true,
      }).then(function (isConfirm) {
          if(isConfirm){
            swal({
            title: 'Actualizado',
            text: 'El usuario fue actualizado satisfactoriamente!',
            icon: 'success'
            }).then(function() {
             $('#formUpdate').submit();
            });
          }
          else{
            //
          }
      })
      });

    </script>
      
    </div>
{% endblock %}

gestorAppTG/templates/user/updatePass.html
{% extends 'template.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <br>
    <h4 class="mb-3">Editar contraseña</h4>
    <div class="row">
      <div class=" col-sm-8 col-12 card text-left p-5" style="margin-left: 15%">
        <form method="post" novalidate>
        {% csrf_token %}
        <b>{{ form|crispy }}</b>
          <div style="margin-bottom: 50px;">
            <button type="submit" class="btn btn-info">Guardar</button>
            <a href="{% url 'users:users_list' %}" class="btn btn-outline-info" role="button">volver</a>
          </div>
        </form>
        </form>
      </div>
    </div>
{% endblock %}