gestorAppTG/gestorAppTG/urls.py
from django.contrib import admin
from django.urls import include,path

#HERICK: importamos todas nuestras vistas aqui 
from .views import gestorAppTG
from .views import propuestas
from .views import user
from .views import tesis
from .views import termin
from .views import defensa
from .views import escuela
from .views import estatusTG
from .views import estatusPropuesta
from .views import reporte
from .views import tranzabilidad

urlpatterns = [
    
    path('', gestorAppTG.home, name='home'),

    path('accounts/', include('django.contrib.auth.urls')),
    
    path('admin/', admin.site.urls,  name="admin"),
    
    path('propuestas/', include(([
        path('', propuestas.IndexView.as_view(), name='propuestas_list'),
        path('<int:pk>/update/', propuestas.UpdatePropuestaView.as_view(), name='propuestas_update'),
        path('search/', propuestas.BusquedaPropuesta.as_view(), name='propuestas_search'),
        path('create/', propuestas.CreatePropuestaView.as_view(), name='propuestas_create'),
        path('<int:pk>/', propuestas.DetailView.as_view(), name='propuestas_details'),
		path('<int:pk>/delete/', propuestas.DeletePropuestaView.as_view(), name='propuestas_delete'),
        path('export/xls/', propuestas.Export_propuesta_xls.export_propuesta_xls, name='export_propuesta_xls'),
    ], 'gestorAppTG'), namespace='propuestas')),

    path('users/', include(([
        path('', user.IndexView.as_view(), name='users_list'),
        path('search/', user.BusquedaUsuario.as_view(), name='users_search'),
        path('<int:pk>/', user.DetailView.as_view(), name='users_details'),
        path('create/', user.CreateUserView.as_view(), name='users_create'),
        path('<int:pk>/update/', user.UpdateUserView.as_view(), name='users_update'),
        path('<int:pk>/updatePass/', user.UpdateUserPassView.as_view(), name='users_updatePass'),
        path('<int:pk>/delete/', user.DeleteUserView.as_view(), name='users_delete'),
        path('export/xls/', user.Export_users_xls.export_users_xls, name='export_users_xls'),
    ], 'gestorAppTG'), namespace='users')),

    path('tesis/', include(([
        path('', tesis.IndexView.as_view(), name='tesis_list'),
        path('search/', tesis.BusquedaTesis.as_view(), name='tesis_search'),
        path('create/', tesis.CreateTesisView.as_view(), name='tesis_create'),
        path('<str:pk>/', tesis.DetailView.as_view(), name='tesis_details'),
        path('<str:pk>/update/', tesis.UpdateTesisView.as_view(), name='tesis_update'),
        path('<str:pk>/delete/', tesis.DeleteTesisView.as_view(), name='tesis_delete'),
        path('export/xls/', tesis.Export_tesis_xls.export_tesis_xls, name='export_tesis_xls'),
    ], 'gestorAppTG'), namespace='tesis')),

    path('defensas/', include(([
        path('', defensa.IndexView.as_view(), name='defensas_list'),
        path('search/', defensa.BusquedaDefensa.as_view(), name='defensas_search'),
        path('create/', defensa.CreateDefensaView.as_view(), name='defensas_create'),
        path('<str:pk>/', defensa.DetailView.as_view(), name='defensas_details'),
        path('<str:pk>/update/', defensa.UpdateDefensaView.as_view(), name='defensas_update'),
        path('<str:pk>/delete/', defensa.DeleteDefensaView.as_view(), name='defensas_delete'),
        path('export/xls/', defensa.Export_defensa_xls.export_defensa_xls, name='export_defensa_xls'),
    ], 'gestorAppTG'), namespace='defensas')),

    path('termin/', include(([
        path('', termin.IndexView.as_view(), name='termins_list'),
        path('create/', termin.CreateTerminView.as_view(), name='termin_create'),
        path('search/', termin.BusquedaTermin.as_view(), name='termin_search'),
        path('<int:pk>/update/', termin.UpdateTerminView.as_view(), name='termin_update'),
        path('<int:pk>/delete/', termin.DeleteTerminView.as_view(), name='termin_delete'),
        path('export/xls/', termin.Export_termin_xls.export_termin_xls, name='export_termin_xls')
    ], 'gestorAppTG'), namespace='termin')),

    path('estatusPropuestas/', include(([
        path('', estatusPropuesta.IndexView.as_view(), name='estatusPropuestas_list'),
        path('create/', estatusPropuesta.CreateEstatusPropuestaView.as_view(), name='estatusPropuestas_create'),
        path('<int:pk>/update/', estatusPropuesta.UpdateEstatusPropuestaView.as_view(), name='estatusPropuestas_update'),
        path('<int:pk>/delete/', estatusPropuesta.DeleteEstatusPropuestaView.as_view(), name='estatusPropuestas_delete'),
        path('export/xls/', estatusPropuesta.Export_estatusPropuesta_xls.export_estatusPropuesta_xls, name='export_estatusPropuesta_xls')
    ], 'gestorAppTG'), namespace='estatusPropuestas')),

    path('estatusTGs/', include(([
        path('', estatusTG.IndexView.as_view(), name='estatusTGs_list'),
        path('create/', estatusTG.CreateEstatusTGView.as_view(), name='estatusTGs_create'),
        path('<int:pk>/update/', estatusTG.UpdateEstatusTGView.as_view(), name='estatusTGs_update'),
        path('<int:pk>/delete/', estatusTG.DeleteEstatusTGView.as_view(), name='estatusTGs_delete'),
         path('export/xls/', estatusTG.Export_estatusTGs_xls.Export_estatusTGs_xls, name='export_estatusTGs_xls')
    ], 'gestorAppTG'), namespace='estatusTGs')),

    path('escuelas/', include(([
        path('', escuela.IndexView.as_view(), name='escuelas_list'),
        path('create/', escuela.CreateEscuelaView.as_view(), name='escuelas_create'),
        path('<int:pk>/update/', escuela.UpdateEscuelaView.as_view(), name='escuelas_update'),
        path('<int:pk>/delete/', escuela.DeleteEscuelaView.as_view(), name='escuelas_delete'),
        path('export/xls/', escuela.Export_escuela_xls.Export_escuela_xls, name='export_escuela_xls')
    ], 'gestorAppTG'), namespace='escuelas')),

    path('tranzabilidad/', include(([
        path('', tranzabilidad.IndexView.as_view(), name='tranzabilidads_list'),
        path('search/', tranzabilidad.BusquedaTranzabilidad.as_view(), name='tranzabilidads_search'),
        path('export/xls/', tranzabilidad.Export_tranzabilidad_xls.Export_tranzabilidad_xls, name='export_tranzabilidad_xls')
    ], 'gestorAppTG'), namespace='tranzabilidads')),

    path('reporte1/', include(([
        path('', reporte.IndexReporte1View.as_view(), name='reporte1s_list'),
         path('export/xls/', reporte.Export_reporte1_xls.Export_reporte1_xls, name='export_reporte1_xls')
    ], 'gestorAppTG'), namespace='reporte1s')),
    path('reporte2/', include(([
        path('', reporte.IndexReporte2View.as_view(), name='reporte2s_list'),
         path('export/xls/', reporte.Export_reporte2_xls.Export_reporte2_xls, name='export_reporte2_xls')
    ], 'gestorAppTG'), namespace='reporte2s')),
    path('reporte3/', include(([
        path('', reporte.IndexReporte3View.as_view(), name='reporte3s_list'),
         path('export/xls/', reporte.Export_reporte3_xls.Export_reporte3_xls, name='export_reporte3_xls')
    ], 'gestorAppTG'), namespace='reporte3s')),
    path('reporte4/', include(([
        path('', reporte.IndexReporte4View.as_view(), name='reporte4s_list'),
         path('export/xls/', reporte.Export_reporte4_xls.Export_reporte4_xls, name='export_reporte4_xls')
    ], 'gestorAppTG'), namespace='reporte4s')),
    path('reporte5/', include(([
        path('', reporte.IndexReporte5View.as_view(), name='reporte5s_list'),
        path('export/xls/', reporte.Export_reporte5_xls.Export_reporte5_xls, name='export_reporte5_xls'),
        path('search/', reporte.Busqueda5.as_view(), name='reporte5_search'),
    ], 'gestorAppTG'), namespace='reporte5s')),
    path('reporte6/', include(([
        path('', reporte.IndexReporte6View.as_view(), name='reporte6s_list'),
        path('export/xls/', reporte.Export_reporte6_xls.Export_reporte6_xls, name='export_reporte6_xls'),
        path('search/', reporte.Busqueda6.as_view(), name='reporte6_search'),
    ], 'gestorAppTG'), namespace='reporte6s')),
    path('reporte7/', include(([
        path('', reporte.IndexReporte7View.as_view(), name='reporte7s_list'),
         path('export/xls/', reporte.Export_reporte7_xls.Export_reporte7_xls, name='export_reporte7_xls')
    ], 'gestorAppTG'), namespace='reporte7s')),
]

gestorAppTG/gestorAppTG/views/defensa.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, Http404
from django.template import loader
from django.contrib import messages
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from ..models import Defensa, Tranzabilidad
from django.utils.decorators import method_decorator
from ..decorador import *
import xlwt
import datetime
from django.db.models import Q


@method_decorator([login_required, invitado_permisos], name='dispatch')
class IndexView(generic.ListView):
    template_name = 'defensa/index.html'
    context_object_name = 'defensa_listass'
    def get_queryset(self):
        p = Tranzabilidad(tipo_de_acccion='se abrio el panel de defensa', usuario=self.request.user,fecha_accion=datetime.datetime.now())
        p.save()
        return Defensa.objects.order_by('id')

@method_decorator([login_required, invitado_permisos], name='dispatch')
class DetailView(generic.DetailView):
    model = Defensa
    template_name = 'defensa/detail.html'

@method_decorator([login_required, gestor_permisos], name='dispatch')
class BusquedaDefensa(generic.ListView):
    template_name = 'defensa/index.html'
    context_object_name = 'defensa_listass'
    def get_queryset(self):
        if self.request.GET:
            search = self.request.GET.get('search')
            p = Tranzabilidad(tipo_de_acccion='consulta de defensa', usuario=self.request.user,fecha_accion=datetime.datetime.now())
            p.save()
            if search == "":
                return Defensa.objects.order_by('id')
        return Defensa.objects.filter(Q(id__contains = str(search)) | Q(tesis__titulo__contains = str(search))) 

@method_decorator([login_required, gestor_permisos], name='dispatch')
class CreateDefensaView(generic.CreateView):
    model = Defensa
    fields = "__all__"
    template_name = 'defensa/create.html'
    def form_valid(self, form):
        defensa = form.save(commit=False)
        defensa.save()
        p = Tranzabilidad(tipo_de_acccion='creo una defensa', usuario=self.request.user,fecha_accion=datetime.datetime.now())
        p.save()
        messages.success(self.request, 'La defensa fue creada exitosamente')
        return redirect('defensas:defensas_list')

@method_decorator([login_required, gestor_permisos], name='dispatch')
class UpdateDefensaView(generic.UpdateView):
    model = Defensa
    fields = "__all__"
    template_name = 'defensa/update.html'
    def form_valid(self, form):
        defensa = form.save(commit=False)
        defensa.save()
        p = Tranzabilidad(tipo_de_acccion='actualizo uan defensa', usuario=self.request.user,fecha_accion=datetime.datetime.now())
        p.save()
        messages.success(self.request, 'La defensa fue actualizada exitosamente')
        return redirect('defensas:defensas_list')

@method_decorator([login_required, gestor_permisos], name='dispatch')
class DeleteDefensaView(generic.DeleteView):
    model = Defensa
    template_name = 'defensa/delete.html'
    def get_success_url(self):
        p = Tranzabilidad(tipo_de_acccion='elimino una defensa', usuario=self.request.user,fecha_accion=datetime.datetime.now())
        p.save()
        return reverse_lazy('defensas:defensas_list')

@method_decorator([login_required, gestor_permisos], name='dispatch')
class Export_defensa_xls(generic.ArchiveIndexView):
    def export_defensa_xls(request):
        model = Defensa
        fields = "__all__"
        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = 'attachment; filename="defensa.xls"'

        wb = xlwt.Workbook(encoding='utf-8')
        ws = wb.add_sheet('defensa')

        # Sheet header, first row
        row_num = 0

        font_style = xlwt.XFStyle()
        font_style.font.bold = True

        columns = ['Id','Fecha Defensa','Jurado 1','Jurado 2','Jurado auxiliar','calificacion','Observaciones','Tesis', ]

        for col_num in range(len(columns)):
            ws.write(row_num, col_num, columns[col_num], font_style)

        # Sheet body, remaining rows
        font_style = xlwt.XFStyle()
        rows = Defensa.objects.all().select_related('jurado_1','jurado_2','jurado_auxiliar','tesis').values_list('id','fecha_defensa','jurado_1__primer_nombre','jurado_2__primer_nombre','jurado_auxiliar__primer_nombre','calificacion','observaciones','tesis__titulo').order_by('observaciones')
        rows = [[x.strftime("%Y-%m-%d %H:%M") if isinstance(x, datetime.datetime) else x for x in row] for row in rows ]
        for row in rows:
            row_num += 1
            for col_num in range(len(row)):
                ws.write(row_num, col_num, row[col_num], font_style)
        p = Tranzabilidad(tipo_de_acccion='exporto en excel las defensas', usuario=request.user,fecha_accion=datetime.datetime.now())
        p.save()
        wb.save(response)
        return response    

gestorAppTG/templates/defensa/create.html
{% extends 'template.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <br>
  <h4 class="mb-3">Crear Defensa</h4>
  <div class="row">
    <div class=" col-sm-8 col-12 card text-left p-5" style="margin-left: 15%">
      <form id="formCreate" method="post" novalidate>
        {% csrf_token %}
        <b>{{ form|crispy }}</b>
        <div style="margin-bottom: 50px;">
            <button id="enviar" type="submit" class="btn btn-info">Guardar</button>
            <a href="{% url 'defensas:defensas_list' %}" class="btn btn-outline-secondary" role="button">
                Volver
            </a>
        </div>
        </form>
      </form>
    </div>
    <script type="text/javascript">
     
     $('#enviar').on('click', function(e){

      id = document.getElementById('id_id').value;
      jurado1 = document.getElementById('id_jurado_1').value;
      jurado2 = document.getElementById('id_jurado_2').value;
      juradoAuxiliar = document.getElementById('id_jurado_auxiliar').value;
      calificacion = document.getElementById('id_calificacion').value;
      fechaCorrecciones = document.getElementById('id_fecha_correciones').value;
      categoriatema = document.getElementById('id_tesis').value;

      if(id == ""){ swal("Error", "Falta el id", "error"); return false;}
      if(jurado1 == ""){ swal("Error", "Falta el jurado 1", "error");  return false;}
      if(jurado2 == ""){ swal("Error", "Falta el jurado 2", "error");  return false;}
      if(juradoAuxiliar == ""){ swal("Error", "Falta el jurado auxiliar", "error"); return false;}
      if(calificacion == ""){ swal("Error", "Falta la calificacion", "error");  return false;}
      if(fechaCorrecciones == ""){swal("Error", "Falta la fecha de correcciones", "error");return false;}
      if(categoriatema == ""){swal("Error", "Falta la categoria del tema", "error");return false;}

      e.preventDefault();
      var $thisForm = $(this).parents('form');
      swal({
        title: 'Estas seguro?',
        text: "Los datos de la defensa seran guardados!",
        icon: 'warning',
        buttons: [
          'No',
          'Yes'
       ],
      dangerMode: true,
      }).then(function (isConfirm) {
          if(isConfirm){
            swal({
            title: 'Creado',
            text: 'La defensa fue creada satisfactoriamente!',
            icon: 'success'
            }).then(function() {
             $('#formCreate').submit();
            });
          }
          else{
            //
          }
      })
      });

    </script>
  </div>
{% endblock %}

gestorAppTG/templates/defensa/delete.html
{% extends 'template.html' %}
{% block content %}
    <form id="deleteForm" method="post">
        {% csrf_token %}
        <p>
            <br>
            <h4 class="mb-3">Eliminar defensa</h4>
            ¿Quieres eliminar esta defensa? 
            <div style="margin-bottom: 50px; margin-top:10px">
                <button id="enviar" type="submit" class="btn btn-info">Guardar</button>
                <a href="{% url 'defensas:defensas_list' %}" class="btn btn-outline-secondary" role="button">Volver
                </a>
            </div>
               <script type="text/javascript">
                 $('#enviar').on('click', function(e){
                  e.preventDefault();
                  swal({
                    title: 'Estas seguro?',
                    text: "Los datos de esta defensa seran eliminados!",
                    icon: 'warning',
                    buttons: [
                      'No',
                      'Yes'
                   ],
                  dangerMode: true,
                  }).then(function (isConfirm) {
                      if(isConfirm){
                        swal({
                        title: 'Actualizado',
                        text: 'Defensa eliminada satisfactoriamente!',
                        icon: 'success'
                        }).then(function() {
                         $('#deleteForm').submit();
                        });
                      }
                      else{
                        //
                      }
                  })
                  });
              </script>
        </p>
    </form>
{% endblock %}

gestorAppTG/templates/defensa/detail.html
{% extends 'template.html' %}
{% block content %}    
    <br>
    <h4>Detalle de la Defensa</h4>
    <p>
        <br>
        <strong>id:&nbsp;</strong> <i>{{ defensa.id }}</i><br>
        <strong>Fecha de la defensa:&nbsp;</strong> <i>{{ defensa.fecha_defensa }}</i><br>
        <strong>jurado1:&nbsp;</strong> <i>{{ defensa.jurado_1 }}</i><br>
        <strong>jurado2:&nbsp;</strong> <i>{{ defensa.jurado_2 }}</i><br>      
        <strong>jurado3:&nbsp;</strong> <i>{{ defensa.jurado_3 }}</i><br>
        <strong>calificacion:&nbsp;</strong> <i>{{ defensa.calificacion }}</i><br>
        <strong>correciones:&nbsp;</strong> <i>{{ defensa.correcciones }}</i><br>
        <strong>Fecha tope de correciones:&nbsp;</strong> <i>{{ defensa.fecha_correciones }}</i><br>
        <strong>¿ es mencion publicacion ?&nbsp;</strong> <i>{{ defensa.mencion_publicacion }}</i><br>
        <strong>¿ es mencion honorifica?&nbsp;</strong> <i>{{ defensa.mencion_honorifica }}</i><br>
        <strong>tesis asociada:&nbsp;</strong> <i>{{ defensa.tesis }}</i><br>
    </p>
    <a href="{% url 'defensas:defensas_list' %}" class="btn btn-outline-info" role="button">
        volver
    </a>
{% endblock %}

gestorAppTG/templates/defensa/index.html
{% extends 'template.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">defensas</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            {% if user.is_authenticated %}
                {% if user.esAdmin or user.esGestor %}
                <a href="" class="btn btn-outline-info" role="button">
                    Exportar pdf
                </a>
                <a href="{% url 'defensas:export_defensa_xls' %}" class="btn btn-outline-info" role="button" style="border-radius: 0 0.25rem 0.25rem 0">
                    Exportar excel
                </a>
                    <a href="{% url 'defensas:defensas_create' %}" class="btn btn-outline-info ml-4" role="button">
                        Crear defensa
                    </a>
                {% endif %}
            {% endif %}
        </div>
        <!--button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
          Exportar proximamente poner este boton Herick
        </button!-->
      </div>
    </div>
    <form action="{% url 'defensas:defensas_search' %}" method="GET" class="form-inline ml-3">
            <div class="cntnr-padding" style="margin-bottom: 15px;margin-top:15px;">
            <div class="row">
               <div class="">
                    <div class="input-group">
                      <input name="search" type="search" value="{{cedula}}" class="form-control" placeholder="Search for...">
                      <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">Search</button>
                      </span>
                    </div>
               </div>
               <div class="col-md-8"></div>
           </div>
        </div>
    </form>

    {% if defensa_listass %}
        <div class="table-responsive">
            <!--{% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}-->
                <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th>Codigo de defensa</th>
                        <th>trabajo de Grado asociado</th>
                        <th>Tesis</th>
                        <th>Calificacion</th>
                        {% if user.is_authenticated %}
                            {% if user.esAdmin or user.esGestor %}
                                <th>Accciones</th>
                            {% endif %}
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for p in defensa_listass %}
                    <tr>
                        <td><a href="{% url 'defensas:defensas_details' p.id %}">{{ p.id }}</a></td>
                        <td>{{p.estatus}}</td>
                        <td>{{p.tesis}}</td>
                        <td>{{p.calificacion}}</td>
                        {% if user.is_authenticated %}
                            {% if user.esAdmin or user.esGestor %}
                            <td>
                                <a href="{% url 'defensas:defensas_update' p.id %}" style="text-decoration: none"><button class="btn btn-primary mb-2">
                                Actualizar
                                </button></a>
                                <a href="{% url 'defensas:defensas_delete' p.id %}" style="text-decoration: none"><button class="btn btn-danger">
                                Eliminar
                                </button></a>
                            </td>
                            {% endif %}
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p>No hay defensas de tesis todavia...</p>
    {% endif %}
{% endblock %}

gestorAppTG/templates/defensa/update.html
{% extends 'template.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <br>
    <h4 class="mb-3">Editar Defensa</h4>
    <div class="row">
      <div class=" col-sm-8 col-12 card text-left p-5" style="margin-left: 15%">
        <form id="formUpdate" method="post" novalidate>
        {% csrf_token %}
        <b>{{ form|crispy }}</b>
          <div style="margin-bottom: 50px;">
            <button id="enviar" type="submit" class="btn btn-success">Guardar</button>
            <a href="{% url 'defensas:defensas_list' %}" class="btn btn-outline-info" role="button">volver</a>
          </div>
        </form>
        </form>
      </div>
      <script type="text/javascript">

        id = document.getElementById('id_id').value;
        jurado1 = document.getElementById('id_jurado_1').value;
        jurado2 = document.getElementById('id_jurado_2').value;
        juradoAuxiliar = document.getElementById('id_jurado_auxiliar').value;
        calificacion = document.getElementById('id_calificacion').value;
        fechaCorrecciones = document.getElementById('id_fecha_correciones').value;
        categoriatema = document.getElementById('id_tesis').value;

        if(id == ""){ swal("Error", "Falta el id", "error"); return false;}
        if(jurado1 == ""){ swal("Error", "Falta el jurado 1", "error");  return false;}
        if(jurado2 == ""){ swal("Error", "Falta el jurado 2", "error");  return false;}
        if(juradoAuxiliar == ""){ swal("Error", "Falta el jurado auxiliar", "error"); return false;}
        if(calificacion == ""){ swal("Error", "Falta la calificacion", "error");  return false;}
        if(fechaCorrecciones == ""){swal("Error", "Falta la fecha de correcciones", "error");return false;}
        if(categoriatema == ""){swal("Error", "Falta la categoria del tema", "error");return false;}

         $('#enviar').on('click', function(e){
          e.preventDefault();
          var $thisForm = $(this).parents('form');
          swal({
            title: 'Estas seguro?',
            text: "Los datos de esta defensa seran cambiados!",
            icon: 'warning',
            buttons: [
              'No',
              'Yes'
           ],
          dangerMode: true,
          }).then(function (isConfirm) {
              if(isConfirm){
                swal({
                title: 'Actualizado',
                text: 'Defensa actualizada satisfactoriamente!',
                icon: 'success'
                }).then(function() {
                 $('#formUpdate').submit();
                });
              }
              else{
                //
              }
          })
          });
      </script>
    </div>
{% endblock %}