gestorAppTG/gestorAppTG/urls.py
from django.contrib import admin
from django.urls import include,path

#HERICK: importamos todas nuestras vistas aqui 
from .views import gestorAppTG
from .views import propuestas
from .views import user
from .views import tesis
from .views import termin
from .views import defensa
from .views import escuela
from .views import estatusTG
from .views import estatusPropuesta
from .views import reporte
from .views import tranzabilidad

urlpatterns = [
    
    path('', gestorAppTG.home, name='home'),

    path('accounts/', include('django.contrib.auth.urls')),
    
    path('admin/', admin.site.urls,  name="admin"),
    
    path('propuestas/', include(([
        path('', propuestas.IndexView.as_view(), name='propuestas_list'),
        path('<int:pk>/update/', propuestas.UpdatePropuestaView.as_view(), name='propuestas_update'),
        path('search/', propuestas.BusquedaPropuesta.as_view(), name='propuestas_search'),
        path('create/', propuestas.CreatePropuestaView.as_view(), name='propuestas_create'),
        path('<int:pk>/', propuestas.DetailView.as_view(), name='propuestas_details'),
		path('<int:pk>/delete/', propuestas.DeletePropuestaView.as_view(), name='propuestas_delete'),
        path('export/xls/', propuestas.Export_propuesta_xls.export_propuesta_xls, name='export_propuesta_xls'),
    ], 'gestorAppTG'), namespace='propuestas')),

    path('users/', include(([
        path('', user.IndexView.as_view(), name='users_list'),
        path('search/', user.BusquedaUsuario.as_view(), name='users_search'),
        path('<int:pk>/', user.DetailView.as_view(), name='users_details'),
        path('create/', user.CreateUserView.as_view(), name='users_create'),
        path('<int:pk>/update/', user.UpdateUserView.as_view(), name='users_update'),
        path('<int:pk>/updatePass/', user.UpdateUserPassView.as_view(), name='users_updatePass'),
        path('<int:pk>/delete/', user.DeleteUserView.as_view(), name='users_delete'),
        path('export/xls/', user.Export_users_xls.export_users_xls, name='export_users_xls'),
    ], 'gestorAppTG'), namespace='users')),

    path('tesis/', include(([
        path('', tesis.IndexView.as_view(), name='tesis_list'),
        path('search/', tesis.BusquedaTesis.as_view(), name='tesis_search'),
        path('create/', tesis.CreateTesisView.as_view(), name='tesis_create'),
        path('<str:pk>/', tesis.DetailView.as_view(), name='tesis_details'),
        path('<str:pk>/update/', tesis.UpdateTesisView.as_view(), name='tesis_update'),
        path('<str:pk>/delete/', tesis.DeleteTesisView.as_view(), name='tesis_delete'),
        path('export/xls/', tesis.Export_tesis_xls.export_tesis_xls, name='export_tesis_xls'),
    ], 'gestorAppTG'), namespace='tesis')),

    path('defensas/', include(([
        path('', defensa.IndexView.as_view(), name='defensas_list'),
        path('search/', defensa.BusquedaDefensa.as_view(), name='defensas_search'),
        path('create/', defensa.CreateDefensaView.as_view(), name='defensas_create'),
        path('<str:pk>/', defensa.DetailView.as_view(), name='defensas_details'),
        path('<str:pk>/update/', defensa.UpdateDefensaView.as_view(), name='defensas_update'),
        path('<str:pk>/delete/', defensa.DeleteDefensaView.as_view(), name='defensas_delete'),
        path('export/xls/', defensa.Export_defensa_xls.export_defensa_xls, name='export_defensa_xls'),
    ], 'gestorAppTG'), namespace='defensas')),

    path('termin/', include(([
        path('', termin.IndexView.as_view(), name='termins_list'),
        path('create/', termin.CreateTerminView.as_view(), name='termin_create'),
        path('search/', termin.BusquedaTermin.as_view(), name='termin_search'),
        path('<int:pk>/update/', termin.UpdateTerminView.as_view(), name='termin_update'),
        path('<int:pk>/delete/', termin.DeleteTerminView.as_view(), name='termin_delete'),
        path('export/xls/', termin.Export_termin_xls.export_termin_xls, name='export_termin_xls')
    ], 'gestorAppTG'), namespace='termin')),

    path('estatusPropuestas/', include(([
        path('', estatusPropuesta.IndexView.as_view(), name='estatusPropuestas_list'),
        path('create/', estatusPropuesta.CreateEstatusPropuestaView.as_view(), name='estatusPropuestas_create'),
        path('<int:pk>/update/', estatusPropuesta.UpdateEstatusPropuestaView.as_view(), name='estatusPropuestas_update'),
        path('<int:pk>/delete/', estatusPropuesta.DeleteEstatusPropuestaView.as_view(), name='estatusPropuestas_delete'),
        path('export/xls/', estatusPropuesta.Export_estatusPropuesta_xls.export_estatusPropuesta_xls, name='export_estatusPropuesta_xls')
    ], 'gestorAppTG'), namespace='estatusPropuestas')),

    path('estatusTGs/', include(([
        path('', estatusTG.IndexView.as_view(), name='estatusTGs_list'),
        path('create/', estatusTG.CreateEstatusTGView.as_view(), name='estatusTGs_create'),
        path('<int:pk>/update/', estatusTG.UpdateEstatusTGView.as_view(), name='estatusTGs_update'),
        path('<int:pk>/delete/', estatusTG.DeleteEstatusTGView.as_view(), name='estatusTGs_delete'),
         path('export/xls/', estatusTG.Export_estatusTGs_xls.Export_estatusTGs_xls, name='export_estatusTGs_xls')
    ], 'gestorAppTG'), namespace='estatusTGs')),

    path('escuelas/', include(([
        path('', escuela.IndexView.as_view(), name='escuelas_list'),
        path('create/', escuela.CreateEscuelaView.as_view(), name='escuelas_create'),
        path('<int:pk>/update/', escuela.UpdateEscuelaView.as_view(), name='escuelas_update'),
        path('<int:pk>/delete/', escuela.DeleteEscuelaView.as_view(), name='escuelas_delete'),
        path('export/xls/', escuela.Export_escuela_xls.Export_escuela_xls, name='export_escuela_xls')
    ], 'gestorAppTG'), namespace='escuelas')),

    path('tranzabilidad/', include(([
        path('', tranzabilidad.IndexView.as_view(), name='tranzabilidads_list'),
        path('search/', tranzabilidad.BusquedaTranzabilidad.as_view(), name='tranzabilidads_search'),
        path('export/xls/', tranzabilidad.Export_tranzabilidad_xls.Export_tranzabilidad_xls, name='export_tranzabilidad_xls')
    ], 'gestorAppTG'), namespace='tranzabilidads')),

    path('reporte1/', include(([
        path('', reporte.IndexReporte1View.as_view(), name='reporte1s_list'),
         path('export/xls/', reporte.Export_reporte1_xls.Export_reporte1_xls, name='export_reporte1_xls')
    ], 'gestorAppTG'), namespace='reporte1s')),
    path('reporte2/', include(([
        path('', reporte.IndexReporte2View.as_view(), name='reporte2s_list'),
         path('export/xls/', reporte.Export_reporte2_xls.Export_reporte2_xls, name='export_reporte2_xls')
    ], 'gestorAppTG'), namespace='reporte2s')),
    path('reporte3/', include(([
        path('', reporte.IndexReporte3View.as_view(), name='reporte3s_list'),
         path('export/xls/', reporte.Export_reporte3_xls.Export_reporte3_xls, name='export_reporte3_xls')
    ], 'gestorAppTG'), namespace='reporte3s')),
    path('reporte4/', include(([
        path('', reporte.IndexReporte4View.as_view(), name='reporte4s_list'),
         path('export/xls/', reporte.Export_reporte4_xls.Export_reporte4_xls, name='export_reporte4_xls')
    ], 'gestorAppTG'), namespace='reporte4s')),
    path('reporte5/', include(([
        path('', reporte.IndexReporte5View.as_view(), name='reporte5s_list'),
        path('export/xls/', reporte.Export_reporte5_xls.Export_reporte5_xls, name='export_reporte5_xls'),
        path('search/', reporte.Busqueda5.as_view(), name='reporte5_search'),
    ], 'gestorAppTG'), namespace='reporte5s')),
    path('reporte6/', include(([
        path('', reporte.IndexReporte6View.as_view(), name='reporte6s_list'),
        path('export/xls/', reporte.Export_reporte6_xls.Export_reporte6_xls, name='export_reporte6_xls'),
        path('search/', reporte.Busqueda6.as_view(), name='reporte6_search'),
    ], 'gestorAppTG'), namespace='reporte6s')),
    path('reporte7/', include(([
        path('', reporte.IndexReporte7View.as_view(), name='reporte7s_list'),
         path('export/xls/', reporte.Export_reporte7_xls.Export_reporte7_xls, name='export_reporte7_xls')
    ], 'gestorAppTG'), namespace='reporte7s')),
]

gestorAppTG/templates/home.html
{% load static %}
<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://i0.wp.com/raw.githubusercontent.com/ServiceStack/Assets/master/img/livedemos/techstacks/django-logo.png?resize=450%2C450&ssl=1&crop=1">
    <title>Gestor de Tesis</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
  </head>

  <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-info fixed-top">
      <a class="navbar-brand" href="/">Proyecto Python </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" >
        {% if not user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link text-white" href="{% url 'login' %}">Login</a>
          </li>
        </ul>
        {% endif %}

        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" style="color:white">Hola {{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}" style="color:white">Cerrar sesión</a>
          </li>
        </ul>
        {% endif %}

      </div>
    </nav>

    <main role="main" class="container" style=" text-align: center;">
      <div class="starter-template" style="padding: 2%">
        <div class="row">
            <div class="col-ml-5 mr-5 p-3 card">
              <img src="{% static 'logo-UCAB.jpg' %}" width="320" height="240">
            </div>

            <div class="col-ml-5">
              <br>
              <h2>Proyecto de Python para la Gestion de TG</h2>
              {% if user.is_authenticated %}
                <br>
                <br>
                  <p> Pagina principal del proyecto, Gracias por iniciar sesion.  </p>
                  <br>
                  <p> Continue utilizando nuestra aplicacion! </p>
                <a href="{% url 'propuestas:propuestas_list' %}" class="btn btn-outline-primary" role="button">
                  Entrar
                </a>
                <br>
              {% else %}
                <br>
              
                  <p> Pagina principal del proyecto, por favor inicie sesion. </p>
                  <p> Aplicacion creada para la electiva de Python. </p>

                  <style type="text/css">
                    .JB-border{
                      border: 1px solid #c0c1c1!important;
                    }
                  </style>
                  
                   <a href="{% url 'login' %}" class="btn btn-primary mb-3" role="button">
                   Iniciar Sesión
                   </a>
                   <table class="table-100w table table-bordered">
                            <tr>
                                <th colspan="2" class="drf-th-center JB-border">
                                    Nombre
                                </th>
                                <th colspan="3" class="drf-th-center JB-border">
                                    Apellido
                                </th>
                                <th colspan="9" class="drf-th-center JB-border">
                                    Cedula
                                </th>
                            </tr>
                            <tr>
                                <td colspan="2" class="drf-td-center JB-border">
                                    Herick
                                </td>
                                <td colspan="3" class="drf-td-center JB-border">
                                    Navarro
                                </td>
                                <td colspan="9" class="drf-td-center JB-border">
                                    24408999
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" class="drf-td-center JB-border">
                                    Jorge
                                </td>
                                <td colspan="3" class="drf-td-center JB-border">
                                    Viloria
                                </td>
                                <td colspan="9" class="drf-td-center JB-border">
                                    27513724
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" class="drf-td-center JB-border">
                                    Ysabel
                                </td>
                                <td colspan="3" class="drf-td-center JB-border">
                                    Ardila
                                </td>
                                <td colspan="9" class="drf-td-center JB-border">
                                    23826183
                                </td>
                            </tr>
                            <tr>
                                <td colspan="2" class="drf-td-center JB-border">
                                    Elias
                                </td>
                                <td colspan="3" class="drf-td-center JB-border">
                                    Barrientos
                                </td>
                                <td colspan="9" class="drf-td-center JB-border">
                                    26089396
                                </td>
                            </tr>
                        </table>
                    </div>
    
                <br>
              {% endif %}
            </div>
        </div>
      </div>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'jquery-3.4.1.slim.min.js' %}"></script>
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

gestorAppTG/templates/template.html
{% load static %}

<!DOCTYPE html>
<!-- saved from url=(0053)https://getbootstrap.com/docs/4.4/examples/dashboard/ -->
<html lang="es">
  
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="generator" content="Jekyll v3.8.6">
  <title>{% block title %} Proyecto Python {% endblock %}</title>
  <link rel="icon" href="https://i0.wp.com/raw.githubusercontent.com/ServiceStack/Assets/master/img/livedemos/techstacks/django-logo.png?resize=450%2C450&ssl=1&crop=1">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
    <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="{% static 'sweetalert.min.js' %}"></script>
    

  <link href="{% static 'dashboard.css' %}" rel="stylesheet">
  <style type="text/css">/* Chart.js */
    @-webkit-keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}@keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}.chartjs-render-monitor{-webkit-animation:chartjs-render-animation 0.001s;animation:chartjs-render-animation 0.001s;}
  </style>
</head>
  
<body>
  <nav class="navbar navbar-dark fixed-top bg-info flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0 text-center" href="/">Proyecto python</a>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link text-white" href="{% url 'logout' %}">Cerrar sesión</a>
    </li>
  </ul>
</nav>
<div class="container-fluid text-center">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          {% if user.is_authenticated %}
            {% if user.esAdmin %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:users_list' %}">
                <span data-feather="users"></span>
                Personas
              </a>
            </li>
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
            {% if user.esAdmin %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tranzabilidads:tranzabilidads_list' %}">
                <span data-feather="users"></span>
                Tranzabilidad usuarios
              </a>
            </li>
            {% endif %}
          {% endif %}


          {% if user.is_authenticated %}
            {% if user.esInvitado or user.esAdmin or user.esGestor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'propuestas:propuestas_list' %}">
                <span data-feather="file"></span>
                Propuestas
              </a>
            </li>
            {% endif %}
          {% endif %}
          {% if user.is_authenticated %}
            {% if user.esInvitado or user.esAdmin or user.esGestor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tesis:tesis_list' %}">
                <span data-feather="home"></span>
                Tesis
              </a>
            </li>
            {% endif %}
          {% endif %}
          {% if user.is_authenticated %}
            {% if user.esInvitado or user.esAdmin or user.esGestor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'defensas:defensas_list' %}">
                <span data-feather="file"></span>
                Defensas
              </a>
            </li>
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
            {% if user.esAdmin  or user.esGestor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'escuelas:escuelas_list' %}">
                <span data-feather="book-open"></span>
                Escuela
              </a>
            </li>
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
            {% if user.esAdmin or user.esGestor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'estatusPropuestas:estatusPropuestas_list' %}">
                <span data-feather="book"></span>
                Estatus de las Propuestas
              </a>
            </li>
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
            {% if user.esAdmin  or user.esGestor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'estatusTGs:estatusTGs_list' %}">
                <span data-feather="book-open"></span>
                Estatus del TG
              </a>
            </li>
            {% endif %}
          {% endif %}

           {% if user.is_authenticated %}
            {% if user.esAdmin  or user.esGestor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'termin:termins_list' %}">
                <span data-feather="clock"></span>
                Terminologías
              </a>
            </li>
            {% endif %}
          {% endif %}
                   
        </ul>
        <h6 class="sidebar-heading justify-content-between align-items-center px-3 mt-4 mb-1 text-muted" style="background-color: fefefe">
          <span>Reportes</span>
          <!-- href="https://getbootstrap.com/docs/4.4/examples/dashboard/#" aria-label="Add a new report"!-->
          <hr>
        </h6>
        <ul class="nav flex-column mb-2">

           {% if user.is_authenticated %}
            {% if user.esAdmin  or user.esGestor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reporte1s:reporte1s_list' %}">
                <span data-feather="clock"></span>
                Reporte 1
              </a>
            </li>
            {% endif %}
          {% endif %}
                   
           {% if user.is_authenticated %}
            {% if user.esAdmin  or user.esGestor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reporte2s:reporte2s_list' %}">
                <span data-feather="clock"></span>
                Reporte 2
              </a>
            </li>
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
            {% if user.esAdmin  or user.esGestor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reporte3s:reporte3s_list' %}">
                <span data-feather="clock"></span>
                Reporte 3
              </a>
            </li>
            {% endif %}
          {% endif %}
          
          {% if user.is_authenticated %}
            {% if user.esAdmin  or user.esGestor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reporte5s:reporte5s_list' %}">
                <span data-feather="clock"></span>
                Reporte 5
              </a>
            </li>
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
            {% if user.esAdmin  or user.esGestor %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reporte6s:reporte6s_list' %}">
                <span data-feather="clock"></span>
                Reporte 6
              </a>
            </li>
            {% endif %}
          {% endif %}           

        </ul>
      </div>
    </nav>
    <main role="main" style="padding-top:0px;"class="col-md-9 ml-sm-auto col-lg-10 px-4"><div class="chartjs-size-monitor" style="position: absolute;  overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
    {% block content %}
    {% endblock %}
    </main>
  </div>
</div>
      <script src="{% static 'jquery-3.4.1.slim.min.js' %}"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
      <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
      <script src="{% static 'feather.min.js' %}"></script>
      <script src="{% static 'Chart.min.js' %}"></script>
      <script src="{% static 'dashboard.js' %}"></script>
</body>

</html>