gestorAppTG/gestorAppTG/urls.py
from django.contrib import admin
from django.urls import include,path

#HERICK: importamos todas nuestras vistas aqui 
from .views import gestorAppTG
from .views import propuestas
from .views import user
from .views import tesis
from .views import termin
from .views import defensa
from .views import escuela
from .views import estatusTG
from .views import estatusPropuesta
from .views import reporte
from .views import tranzabilidad

urlpatterns = [
    
    path('', gestorAppTG.home, name='home'),

    path('accounts/', include('django.contrib.auth.urls')),
    
    path('admin/', admin.site.urls,  name="admin"),
    
    path('propuestas/', include(([
        path('', propuestas.IndexView.as_view(), name='propuestas_list'),
        path('<int:pk>/update/', propuestas.UpdatePropuestaView.as_view(), name='propuestas_update'),
        path('search/', propuestas.BusquedaPropuesta.as_view(), name='propuestas_search'),
        path('create/', propuestas.CreatePropuestaView.as_view(), name='propuestas_create'),
        path('<int:pk>/', propuestas.DetailView.as_view(), name='propuestas_details'),
		path('<int:pk>/delete/', propuestas.DeletePropuestaView.as_view(), name='propuestas_delete'),
        path('export/xls/', propuestas.Export_propuesta_xls.export_propuesta_xls, name='export_propuesta_xls'),
    ], 'gestorAppTG'), namespace='propuestas')),

    path('users/', include(([
        path('', user.IndexView.as_view(), name='users_list'),
        path('search/', user.BusquedaUsuario.as_view(), name='users_search'),
        path('<int:pk>/', user.DetailView.as_view(), name='users_details'),
        path('create/', user.CreateUserView.as_view(), name='users_create'),
        path('<int:pk>/update/', user.UpdateUserView.as_view(), name='users_update'),
        path('<int:pk>/updatePass/', user.UpdateUserPassView.as_view(), name='users_updatePass'),
        path('<int:pk>/delete/', user.DeleteUserView.as_view(), name='users_delete'),
        path('export/xls/', user.Export_users_xls.export_users_xls, name='export_users_xls'),
    ], 'gestorAppTG'), namespace='users')),

    path('tesis/', include(([
        path('', tesis.IndexView.as_view(), name='tesis_list'),
        path('search/', tesis.BusquedaTesis.as_view(), name='tesis_search'),
        path('create/', tesis.CreateTesisView.as_view(), name='tesis_create'),
        path('<str:pk>/', tesis.DetailView.as_view(), name='tesis_details'),
        path('<str:pk>/update/', tesis.UpdateTesisView.as_view(), name='tesis_update'),
        path('<str:pk>/delete/', tesis.DeleteTesisView.as_view(), name='tesis_delete'),
        path('export/xls/', tesis.Export_tesis_xls.export_tesis_xls, name='export_tesis_xls'),
    ], 'gestorAppTG'), namespace='tesis')),

    path('defensas/', include(([
        path('', defensa.IndexView.as_view(), name='defensas_list'),
        path('search/', defensa.BusquedaDefensa.as_view(), name='defensas_search'),
        path('create/', defensa.CreateDefensaView.as_view(), name='defensas_create'),
        path('<str:pk>/', defensa.DetailView.as_view(), name='defensas_details'),
        path('<str:pk>/update/', defensa.UpdateDefensaView.as_view(), name='defensas_update'),
        path('<str:pk>/delete/', defensa.DeleteDefensaView.as_view(), name='defensas_delete'),
        path('export/xls/', defensa.Export_defensa_xls.export_defensa_xls, name='export_defensa_xls'),
    ], 'gestorAppTG'), namespace='defensas')),

    path('termin/', include(([
        path('', termin.IndexView.as_view(), name='termins_list'),
        path('create/', termin.CreateTerminView.as_view(), name='termin_create'),
        path('search/', termin.BusquedaTermin.as_view(), name='termin_search'),
        path('<int:pk>/update/', termin.UpdateTerminView.as_view(), name='termin_update'),
        path('<int:pk>/delete/', termin.DeleteTerminView.as_view(), name='termin_delete'),
        path('export/xls/', termin.Export_termin_xls.export_termin_xls, name='export_termin_xls')
    ], 'gestorAppTG'), namespace='termin')),

    path('estatusPropuestas/', include(([
        path('', estatusPropuesta.IndexView.as_view(), name='estatusPropuestas_list'),
        path('create/', estatusPropuesta.CreateEstatusPropuestaView.as_view(), name='estatusPropuestas_create'),
        path('<int:pk>/update/', estatusPropuesta.UpdateEstatusPropuestaView.as_view(), name='estatusPropuestas_update'),
        path('<int:pk>/delete/', estatusPropuesta.DeleteEstatusPropuestaView.as_view(), name='estatusPropuestas_delete'),
        path('export/xls/', estatusPropuesta.Export_estatusPropuesta_xls.export_estatusPropuesta_xls, name='export_estatusPropuesta_xls')
    ], 'gestorAppTG'), namespace='estatusPropuestas')),

    path('estatusTGs/', include(([
        path('', estatusTG.IndexView.as_view(), name='estatusTGs_list'),
        path('create/', estatusTG.CreateEstatusTGView.as_view(), name='estatusTGs_create'),
        path('<int:pk>/update/', estatusTG.UpdateEstatusTGView.as_view(), name='estatusTGs_update'),
        path('<int:pk>/delete/', estatusTG.DeleteEstatusTGView.as_view(), name='estatusTGs_delete'),
         path('export/xls/', estatusTG.Export_estatusTGs_xls.Export_estatusTGs_xls, name='export_estatusTGs_xls')
    ], 'gestorAppTG'), namespace='estatusTGs')),

    path('escuelas/', include(([
        path('', escuela.IndexView.as_view(), name='escuelas_list'),
        path('create/', escuela.CreateEscuelaView.as_view(), name='escuelas_create'),
        path('<int:pk>/update/', escuela.UpdateEscuelaView.as_view(), name='escuelas_update'),
        path('<int:pk>/delete/', escuela.DeleteEscuelaView.as_view(), name='escuelas_delete'),
        path('export/xls/', escuela.Export_escuela_xls.Export_escuela_xls, name='export_escuela_xls')
    ], 'gestorAppTG'), namespace='escuelas')),

    path('tranzabilidad/', include(([
        path('', tranzabilidad.IndexView.as_view(), name='tranzabilidads_list'),
        path('search/', tranzabilidad.BusquedaTranzabilidad.as_view(), name='tranzabilidads_search'),
        path('export/xls/', tranzabilidad.Export_tranzabilidad_xls.Export_tranzabilidad_xls, name='export_tranzabilidad_xls')
    ], 'gestorAppTG'), namespace='tranzabilidads')),

    path('reporte1/', include(([
        path('', reporte.IndexReporte1View.as_view(), name='reporte1s_list'),
         path('export/xls/', reporte.Export_reporte1_xls.Export_reporte1_xls, name='export_reporte1_xls')
    ], 'gestorAppTG'), namespace='reporte1s')),
    path('reporte2/', include(([
        path('', reporte.IndexReporte2View.as_view(), name='reporte2s_list'),
         path('export/xls/', reporte.Export_reporte2_xls.Export_reporte2_xls, name='export_reporte2_xls')
    ], 'gestorAppTG'), namespace='reporte2s')),
    path('reporte3/', include(([
        path('', reporte.IndexReporte3View.as_view(), name='reporte3s_list'),
         path('export/xls/', reporte.Export_reporte3_xls.Export_reporte3_xls, name='export_reporte3_xls')
    ], 'gestorAppTG'), namespace='reporte3s')),
    path('reporte4/', include(([
        path('', reporte.IndexReporte4View.as_view(), name='reporte4s_list'),
         path('export/xls/', reporte.Export_reporte4_xls.Export_reporte4_xls, name='export_reporte4_xls')
    ], 'gestorAppTG'), namespace='reporte4s')),
    path('reporte5/', include(([
        path('', reporte.IndexReporte5View.as_view(), name='reporte5s_list'),
        path('export/xls/', reporte.Export_reporte5_xls.Export_reporte5_xls, name='export_reporte5_xls'),
        path('search/', reporte.Busqueda5.as_view(), name='reporte5_search'),
    ], 'gestorAppTG'), namespace='reporte5s')),
    path('reporte6/', include(([
        path('', reporte.IndexReporte6View.as_view(), name='reporte6s_list'),
        path('export/xls/', reporte.Export_reporte6_xls.Export_reporte6_xls, name='export_reporte6_xls'),
        path('search/', reporte.Busqueda6.as_view(), name='reporte6_search'),
    ], 'gestorAppTG'), namespace='reporte6s')),
    path('reporte7/', include(([
        path('', reporte.IndexReporte7View.as_view(), name='reporte7s_list'),
         path('export/xls/', reporte.Export_reporte7_xls.Export_reporte7_xls, name='export_reporte7_xls')
    ], 'gestorAppTG'), namespace='reporte7s')),
]

gestorAppTG/gestorAppTG/views/propuesta.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, Http404
from django.template import loader
from django.contrib import messages
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from ..models import Propuesta
from django.utils.decorators import method_decorator
from ..decorador import *


@method_decorator([login_required, invitado_permisos], name='dispatch')
class IndexView(generic.ListView):
    template_name = 'propuesta/index.html'
    context_object_name = 'propuestas_ultimos'
    
    def get_queryset(self):
        return Propuesta.objects.order_by('entrega_fecha')[:5]

@method_decorator([login_required, invitado_permisos], name='dispatch')
class DetailView(generic.DetailView):
    model = Propuesta
    template_name = 'propuesta/detail.html'

@method_decorator([login_required, manager_permisos], name='dispatch')
class CreatePropuestaView(generic.CreateView):
    model = Propuesta
    fields = "__all__"
    template_name = 'propuesta/create.html'
    def formu_valido(self, form):
        propuesta = form.save(commit=False)
        propuesta.save()
        messages.success(self.request, 'La propuesta fue creada exitosamente')
        return redirect('propuestas:propuestas_list')

@method_decorator([login_required, manager_permisos], name='dispatch')
class UpdatePropuestaView(generic.UpdateView):
    model = Propuesta
    fields = "__all__"
    template_name = 'propuesta/update.html'
    def formu_valido(self, form):
        propuesta = form.save(commit=False)
        propuesta.save()
        messages.success(self.request, 'La propuesta fue actualizada exitosamente')
        return redirect('propuestas:propuestas_list')

@method_decorator([login_required, manager_permisos], name='dispatch')
class DeletePropuestaView(generic.DeleteView):
    model = propuesta
    template_name = 'propuesta/delete.html'
    success_url = reverse_lazy('propuestas:propuestas_list')

gestorAppTG/gestorAppTG/views/propuestas.py
from django.shortcuts import get_object_or_404, redirect, render
from django.http import HttpResponse, Http404
from django.template import loader
from django.contrib import messages
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from ..models import Propuesta,EstatusPropuesta, Tranzabilidad
from django.utils.decorators import method_decorator
from ..decorador import *
from django import forms
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _
import xlwt
import datetime

@method_decorator([login_required, invitado_permisos], name='dispatch')
class IndexView(generic.ListView):
    template_name = 'propuestas/index.html'
    context_object_name = 'propuestas_listass'
    
    def get_queryset(self):    
        p = Tranzabilidad(tipo_de_acccion='consulto el panel de propuesta', usuario=self.request.user,fecha_accion=datetime.datetime.now())
        p.save()
        return Propuesta.objects.order_by('entrega_fecha')

@method_decorator([login_required, invitado_permisos], name='dispatch')
class DetailView(generic.DetailView):
    model = Propuesta
    template_name = 'propuestas/detail.html'

@method_decorator([login_required, gestor_permisos], name='dispatch')
class BusquedaPropuesta(generic.ListView):
    template_name = 'propuestas/index.html'
    context_object_name = 'propuestas_listass'
    def get_queryset(self):
        if self.request.GET:
            search = self.request.GET.get('search')
            p = Tranzabilidad(tipo_de_acccion='busco una propuesta', usuario=self.request.user,fecha_accion=datetime.datetime.now())
            p.save()
            if search == "":
                return Propuesta.objects.order_by('entrega_fecha')
        return Propuesta.objects.filter(Q(titulo__contains = str(search)) | Q(estatus__nombre__contains = str(search))) 

@method_decorator([login_required, gestor_permisos], name='dispatch')
class CreatePropuestaView(generic.CreateView):
    model = Propuesta
    fields = "__all__"
    template_name = 'propuestas/create.html'

    def form_valid(self, form):
        propuesta = form.save(commit=False)
        if(propuesta.estudiante_1.getId()== propuesta.estudiante_2.getId()):
            messages.error(self.request, 'Error no puede ser el mismo estudiante en la misma propuesta.')
            return redirect('propuestas:propuestas_create',my_function)
        else:    
            propuesta.save()
            p = Tranzabilidad(tipo_de_acccion='creo una propuesta', usuario=self.request.user,fecha_accion=datetime.datetime.now())
            p.save()
            messages.success(self.request, 'La propuesta fue creada exitosamente')
            return redirect('propuestas:propuestas_list')

@method_decorator([login_required, gestor_permisos], name='dispatch')
class UpdatePropuestaView(generic.UpdateView):
    model = Propuesta
    fields = "__all__"
    template_name = 'propuestas/update.html'
    def form_valid(self, form):
        propuesta = form.save(commit=False)
        propuesta.save()
        p = Tranzabilidad(tipo_de_acccion='actualizo una propuesta', usuario=self.request.user,fecha_accion=datetime.datetime.now())
        p.save()
        messages.success(self.request, 'La propuesta fue actualizada exitosamente')
        return redirect('propuestas:propuestas_list')

@method_decorator([login_required, gestor_permisos], name='dispatch')
class DeletePropuestaView(generic.DeleteView):
    model = Propuesta
    template_name = 'propuestas/delete.html'
    def get_success_url(self):
        p = Tranzabilidad(tipo_de_acccion='elimino una tesis', usuario=self.request.user,fecha_accion=datetime.datetime.now())
        p.save()
        return reverse_lazy('propuestas:propuestas_list')


@method_decorator([login_required, gestor_permisos], name='dispatch')
class Export_propuesta_xls(generic.ArchiveIndexView):
    def export_propuesta_xls(request):
        model = Propuesta
        fields = "__all__"
        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = 'attachment; filename="propuestas.xls"'

        wb = xlwt.Workbook(encoding='utf-8')
        ws = wb.add_sheet('Users')

        # Sheet header, first row
        row_num = 0

        font_style = xlwt.XFStyle()
        font_style.font.bold = True

        columns = ['Título', 'Estatus', 'Escuela','Fecha de entrega','Estudiante 1 apellido','Estudiante 1 nombre','Estudiante 2 apellido','Estudiante 2 nombre','Tutor academico apellido','tutor academico nombre','Tutor empresarial apellido','Tutor empresarial nombre','Termin', ]

        for col_num in range(len(columns)):
            ws.write(row_num, col_num, columns[col_num], font_style)

        # Sheet body, remaining rows
        font_style = xlwt.XFStyle()
        rows = Propuesta.objects.all().select_related('estatus','escuela','estudiante_1','estudiante_2','tutor_academico','tutor_empresa','termin').values_list('titulo','estatus__nombre','escuela__nombre','entrega_fecha','estudiante_1__primer_apellido','estudiante_1__primer_nombre','estudiante_2__primer_apellido','estudiante_2__primer_nombre','tutor_academico__primer_apellido','tutor_academico__primer_nombre','tutor_empresa__primer_apellido','tutor_empresa__primer_nombre','termin__descripcion').order_by('estatus_id')
        
        rows = [[x.strftime("%Y-%m-%d %H:%M") if isinstance(x, datetime.datetime) else x for x in row] for row in rows ]
        for row in rows:
            row_num += 1
            for col_num in range(len(row)):
                ws.write(row_num, col_num, row[col_num], font_style)
        p = Tranzabilidad(tipo_de_acccion='exporto en excel las propuestas', usuario=request.user,fecha_accion=datetime.datetime.now())
        p.save()
        wb.save(response)
        return response

gestorAppTG/templates/propuestas/create.html
{% extends 'template.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <br>
  <h4 class="mb-3">Crear propuestas</h4>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
  <div class="row">
    <div class=" col-sm-8 col-12 card text-left p-5" style="margin-left: 15%">
      <form id="formCreate" method="post" novalidate>
        {% csrf_token %}
        <b>{{ form|crispy }}</b>
<!-- 
TODO: ELIAS: en el campo de estatus de la propuesta poner un droplist con los valores: 
* Por evaluar
* Diferida
* Aprobada
* Rechazada
  </!-->

        <div style="margin-bottom: 50px;">
            <button id="enviar" type="submit" class="btn btn-success">Guardar</button>
            <a href="{% url 'propuestas:propuestas_list' %}" class="btn btn-outline-info" role="button">
                Volver
            </a>
        </div>
        </form>

         <script type="text/javascript">

     $('#enviar').on('click', function(e){

      idFecha = document.getElementById('id_entrega_fecha').value;
      idTitulo = document.getElementById('id_titulo').value;
      idEscuela = document.getElementById('id_escuela').value;
      idStatus = document.getElementById('id_estatus').value;
      idEst = document.getElementById('id_estudiante_1').value;
      idTutorAcademico = document.getElementById('id_tutor_academico').value;
      idTutorEmpresa = document.getElementById('id_tutor_empresa').value;
      idTerm = document.getElementById('id_termin').value;

      if(idFecha == ""){ swal("Error", "Falta la fecha de entrega", "error"); return false;}
      if(idTitulo == ""){ swal("Error", "Falta el titulo", "error");  return false;}
      if(idStatus == ""){ swal("Error", "Falta el estatus", "error");  return false;}
      if(idEscuela == ""){ swal("Error", "Falta la escuela asociada", "error"); return false;}
      if(idEst == ""){ swal("Error", "Escriba por lo menos un estudiante", "error");  return false;}
      if(idTutorAcademico == ""){swal("Error", "Falta el tutor academico", "error");return false;}
      if(idTutorEmpresa == ""){swal("Error", "Falta el tutor de empresa", "error");return false;}
      if(idTerm == ""){swal("Error", "Seleccione alguna terminologia", "error");return false;}

      e.preventDefault();
      var $thisForm = $(this).parents('form');
      swal({
        title: 'Estas seguro?',
        text: "Los datos de la propuesta seran guardados!",
        icon: 'warning',
        buttons: [
          'No',
          'Yes'
       ],
      dangerMode: true,
      }).then(function (isConfirm) {
          if(isConfirm){
            swal({
            title: 'Creado',
            text: 'La propuesta fue creada satisfactoriamente!',
            icon: 'success'
            }).then(function() {
             $('#formCreate').submit();
            });
          }
          else{
            //
          }
      })
      });

    </script>
    </div>
  </div>
{% endblock %}

gestorAppTG/templates/propuestas/delete.html
{% extends 'template.html' %}
{% block content %}
    <form id="deleteForm" method="post">
        {% csrf_token %}
        <p>
            <br>
            <h4 class="mb-3">Eliminar propuesta</h4>
            ¿Quieres eliminar esta propuesta? 
            <div style="margin-bottom: 50px; margin-top:10px">
                <button id="enviar" type="submit" class="btn btn-info">Guardar</button>
                <a href="{% url 'propuestas:propuestas_list' %}" class="btn btn-outline-info" role="button">Volver
                </a>
            </div>
            <script type="text/javascript">
                 $('#enviar').on('click', function(e){
                  e.preventDefault();
                  swal({
                    title: 'Estas seguro?',
                    text: "Los datos de esta propuesta seran eliminados!",
                    icon: 'warning',
                    buttons: [
                      'No',
                      'Yes'
                   ],
                  dangerMode: true,
                  }).then(function (isConfirm) {
                      if(isConfirm){
                        swal({
                        title: 'Actualizado',
                        text: 'Propuesta eliminada satisfactoriamente!',
                        icon: 'success'
                        }).then(function() {
                         $('#deleteForm').submit();
                        });
                      }
                      else{
                        //
                      }
                  })
                  });
              </script>
        </p>
    </form>
{% endblock %}

gestorAppTG/templates/propuestas/detail.html
{% extends 'template.html' %}
{% block content %}    
    <br>
    <h4>Detalle de la propuesta</h4>
    <p>
        <br>
        <strong>Título:&nbsp;</strong> <i>{{ propuesta.titulo }}</i><br>
        <strong>Fecha:&nbsp;</strong> <i>{{ propuesta.entrega_fecha }}</i><br>
        <strong>Estatus:&nbsp;</strong> <i>{{ propuesta.estatus }}</i><br>
        <strong>Estudiante 1:&nbsp;</strong> <i>{{ propuesta.estudiante_1 }}</i><br>      
        <strong>Estudiante 2:&nbsp;</strong> <i>{{ propuesta.estudiante_2 }}</i><br>
        <strong>Tutor académico:&nbsp;</strong> <i>{{ propuesta.tutor_academico }}</i><br>
        <strong>Tutor empresarial:&nbsp;</strong> <i>{{ propuesta.tutor_empresa }}</i><br>
        <strong>Terminología:&nbsp;</strong> <i>{{ propuesta.termin }}</i><br>
    </p>
    <a href="{% url 'propuestas:propuestas_list' %}" class="btn btn-outline-info" role="button">
        volver
    </a>
{% endblock %}

gestorAppTG/templates/propuestas/index.html
{% extends 'template.html' %}
{% block content %}
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Propuestas</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
            {% if user.is_authenticated %}
                {% if user.esAdmin or user.esGestor %}
                <a href="" class="btn btn-outline-info" role="button">
                    Exportar pdf
                </a>
                <a href="{% url 'propuestas:export_propuesta_xls' %}" class="btn btn-outline-info" role="button" style="border-radius: 0 0.25rem 0.25rem 0">
                    Exportar excel
                </a>


                    <a href="{% url 'propuestas:propuestas_create' %}" class="btn btn-outline-info ml-4" role="button">
                        Crear propuesta
                    </a>
                {% endif %}
            {% endif %}
        </div>
        <!--button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
          Exportar proximamente poner este boton Herick
        </button!-->
      </div>
    </div>
    
    <form action="{% url 'propuestas:propuestas_search' %}" method="GET" class="form-inline ml-3">
            <div class="cntnr-padding" style="margin-bottom: 15px;margin-top:15px;">
            <div class="row">
               <div class="">
                    <div class="input-group">
                      <input name="search" type="search" value="{{cedula}}" class="form-control" placeholder="Search for...">
                      <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">Search</button>
                      </span>
                    </div>
               </div>
               <div class="col-md-8"></div>
           </div>
        </div>
    </form>

    {% if propuestas_listass %}
        <div class="table-responsive">
            <!-- {% if messages %}
            <ul class="messages">
              {% for message in messages %}
              <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
              {% endfor %}
            </ul>
            {% endif %} -->
            <table class="table table-striped table-sm">
                <thead>
                    <tr>
                        <th class="text-center" style="max-width:250px;"> Título</th>
                        <th>Estatus</th>
                        <th>Fecha de la propuesta</th>
                        {% if user.is_authenticated %}
                            {% if user.esAdmin or user.esGestor %}
                                <th>Acciones</th>
                            {% endif %}
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for p in propuestas_listass %}
                    <tr>
                        <td class="text-center p-2"style="max-width:250px;"  ><a href="{% url 'propuestas:propuestas_details' p.id %}">{{ p.titulo }}</a></td>
                        <td >{{p.estatus}}</td>
                        <td>{{p.entrega_fecha}}</td>
                        {% if user.is_authenticated %}
                            {% if user.esAdmin or user.esGestor %}
                            <td>
                                <a href="{% url 'propuestas:propuestas_update' p.id %}" style="text-decoration: none">
                                    <button class="btn btn-primary">
                                        Actualizar
                                    </button>
                                </a>
                                <a href="{% url 'propuestas:propuestas_delete' p.id %}" style="text-decoration: none">
                                    <button class="btn btn-danger">
                                        Eliminar
                                    </button>
                                </a>
                            </td>
                            {% endif %}
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <p>No hay propuestas de tesis todavia...</p>
    {% endif %}
{% endblock %}

gestorAppTG/templates/propuestas/update.html
{% extends 'template.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <br>
    <h4 class="mb-3">Editar propuestas</h4>
    <div class="row">
      <div class=" col-sm-8 col-12 card text-left p-5" style="margin-left: 15%">
        <form id="formUpdate" method="post" novalidate>
        {% csrf_token %}
        <b>{{ form|crispy }}</b>
<!-- 
TODO: ELIAS: en el campo de estatus de la propuesta poner un droplist con los valores: 
* Por evaluar
* Diferida
* Aprobada
* Rechazada
  </!-->
          <div style="margin-bottom: 50px;">
            <button id="enviar" type="submit" class="btn btn-info">Guardar</button>
            <a href="{% url 'propuestas:propuestas_list' %}" class="btn btn-outline-info" role="button">volver</a>
          </div>
        </form>
        </form>
      </div>

    <script type="text/javascript">

     $('#enviar').on('click', function(e){

      idFecha = document.getElementById('id_entrega_fecha').value;
      idTitulo = document.getElementById('id_titulo').value;
      idEscuela = document.getElementById('id_escuela').value;
      idStatus = document.getElementById('id_estatus').value;
      idEst = document.getElementById('id_estudiante_1').value;
      idTutorAcademico = document.getElementById('id_tutor_academico').value;
      idTutorEmpresa = document.getElementById('id_tutor_empresa').value;
      idTerm = document.getElementById('id_termin').value;

      if(idFecha == ""){ swal("Error", "Falta la fecha de entrega", "error"); return false;}
      if(idTitulo == ""){ swal("Error", "Falta el titulo", "error");  return false;}
      if(idStatus == ""){ swal("Error", "Falta el estatus", "error");  return false;}
      if(idEscuela == ""){ swal("Error", "Falta la escuela asociada", "error"); return false;}
      if(idEst == ""){ swal("Error", "Escriba por lo menos un estudiante", "error");  return false;}
      if(idTutorAcademico == ""){swal("Error", "Falta el tutor academico", "error");return false;}
      if(idTutorEmpresa == ""){swal("Error", "Falta el tutor de empresa", "error");return false;}
      if(idTerm == ""){swal("Error", "Seleccione alguna terminologia", "error");return false;}
      
      e.preventDefault();
      var $thisForm = $(this).parents('form');
      swal({
        title: 'Estas seguro?',
        text: "Los datos de la propuesta seran modificados!",
        icon: 'warning',
        buttons: [
          'No',
          'Yes'
       ],
      dangerMode: true,
      }).then(function (isConfirm) {
          if(isConfirm){
            swal({
            title: 'Actualizado',
            text: 'La propuesta fue actualizada satisfactoriamente!',
            icon: 'success'
            }).then(function() {
             $('#formUpdate').submit();
            });
          }
          else{
            //
          }
      })
      });

    </script>
    </div>
{% endblock %}